!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers:
- mHandle: 212
  mName: SPI NavX X Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 213
  mName: SPI NavX Y Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 214
  mName: SPI NavX Z Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers:
  4: NavX
mDigitalIO: []
mEncoders: []
mGyros:
- mHandle: 212
  mName: SPI NavX Yaw
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 213
  mName: SPI NavX Pitch
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 214
  mName: SPI NavX Roll
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
mPwm:
- mHandle: 0
  mMotorModelConfig:
    mGearReduction: 7.31
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 90.0
  mName: Speed Controller 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 1
  mMotorModelConfig:
    mGearReduction: 7.31
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 0.09
  mName: Speed Controller 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 2
  mMotorModelConfig:
    mGearReduction: 7.31
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 90.0
  mName: Speed Controller 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 3
  mMotorModelConfig:
    mGearReduction: 7.31
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 90.0
  mName: Speed Controller 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
mRelays: []
mSimulatorComponents: []
mSolenoids: []
